---
abstract: 'Perl distribution for libvas'
author:
  - 'Ahmad Fatoum <athreef@cpan.org>'
build_requires:
  Alien::CMake: '0.07'
  ExtUtils::CBuilder: '0'
  IO::Socket::SSL: '0'
  Test2: '1.302015'
  Test2::Bundle::More: '0'
  Test2::Suite: '0.000030'
  Test::Alien: '0.05'
configure_requires:
  Alien::Base::ModuleBuild: '0'
  Alien::CMake: '0.07'
  Module::Build: '0'
dynamic_config: 1
generated_by: 'Module::Build version 0.422, CPAN::Meta::Converter version 2.150005'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Alien-libvas
provides:
  Alien::libvas:
    file: lib/Alien/libvas.pm
    version: '0.12'
recommends:
  IO::Socket::SSL: '0'
requires:
  Alien::Base: '0.030'
  File::ShareDir: '1.00'
  perl: '5.008001'
resources:
  license: http://dev.perl.org/licenses/
version: '0.12'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
